### ISSUE TITLE
React: authentication story

### ISSUE THREAD

**Issue by maorleger** [maorleger/azure-sdk-experiments#3]
I just did the first thing that worked, but I believe I'm handling browser auth wrong.

1. I think using defaultAzureCredential is the right thing to do in this context, right? 
2. I think new'ing up an InteractiveBrowserCredential for every service isn't the right thing to do. I noticed way more auth calls than I expected
3. If a user fails to auth I just dump the error to the console, is there a better handling strategy?

**Comment by ogeobubu** [comment]
Have you heard of error boundaries? Error boundaries are components in React that catch JavaScript errors anywhere in their child component tree.

According to the documentation,

```
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // Update state so the next render will show the fallback UI.
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    // You can also log the error to an error reporting service
    logErrorToMyService(error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      // You can render any custom fallback UI
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children; 
  }
}
```

Then you can use it as a regular component. It is also helpful in auth

**Comment by maorleger** [comment]
Thank you so much! I'll definitely read up on that
